### ISSUE TITLE
Need Installation File for Ubuntu 16.04

### ISSUE THREAD

**Issue by madhu6759** [medkey-org/medkey#6]
Hello,
Any one help me to install the medkey app in my ubuntu 16.04 server.Need installation guide.

**Comment by dgrudinin** [comment]
You can use this instruction for installation of Medkey from source code (current repo version is v1):

https://medkey.org/ru/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0_%D0%9C%D0%B5%D0%B4%D0%BA%D0%B5%D0%B9_v1_%D0%BD%D0%B0_Debian_9

Now it is in russian, but you can use google or any another translator.
