### ISSUE TITLE
In medkey after data migration how to create a username and password for login.

### ISSUE THREAD

**Issue by madhu6759** [medkey-org/medkey#7]

**Comment by dgrudinin** [comment]
In CLI execute in the application root directory next commands:

* `php bin cli/seed package install` 
* `php bin cli/seed acl install`
* `php bin cli/seed user insall`

It will create admin:admin record, after login you can change default password.

**Comment by madhu6759** [comment]
Hello, I m sorry, I didn't understand. please help me

**Comment by dgrudinin** [comment]
> Hello, I m sorry, I didn't understand. please help me

Run your OS terminal (sh, bash) and execute that commands, one by one. How can I help you more to understand it?

**Comment by madhu6759** [comment]
i am running it on ubuntu 16.04 server.

**Comment by madhu6759** [comment]
kindly help me sir.

**Comment by dgrudinin** [comment]
> i am running it on ubuntu 16.04 server.

1. Run Terminal (https://askubuntu.com/questions/183775/how-do-i-open-a-terminal). 
2. Then go to your medkey application directory (for default Medkey installation — /var/www/medkey).
you can make it by executing command: cd /var/www/medkey
3. Execute said in previous comment (↑) three commands, being inside that Medkey application directory (/var/www/medkey).
4. Open your browser's URL and login using admin:admin.

**Comment by madhu6759** [comment]
![medkey1](https://user-images.githubusercontent.com/46740847/53090261-da62f280-3534-11e9-9112-9d74e91a00fb.PNG)

I am getting these error!

**Comment by madhu6759** [comment]
kindly help me.

**Comment by dgrudinin** [comment]
> ![medkey1](https://user-images.githubusercontent.com/46740847/53090261-da62f280-3534-11e9-9112-9d74e91a00fb.PNG)
> 
> I am getting these error!

Looks like you trying to install Medkey v0.2.0. I thought that you want to install latest version from repository.

Then run single command `php medkey seed package install`.

**Comment by madhu6759** [comment]
Wow!!!it works thank you....

**Comment by madhu6759** [comment]
Can you please send me the latest version medkey link ....

**Comment by dgrudinin** [comment]
> Can you please send me the latest version medkey link ....

You can download latest Medkey version from repository. And can install it by following steps from this manual — https://medkey.org/ru/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0_%D0%9C%D0%B5%D0%B4%D0%BA%D0%B5%D0%B9_v1_%D0%BD%D0%B0_Debian_9 (manual in Russian, but commands international).

**Comment by dgrudinin** [comment]
Click star for repo or medkey-org at github if you're satisfied. With best regards!

**Comment by madhu6759** [comment]
Hi Dude,
I have installed the latest version of medkey. when I use  php bin cli/migrate this command i receive Unknown command: cli/migrate error.kindly help me.

**Comment by madhu6759** [comment]
In latest medkey file, migrations folder is empty.

**Comment by dgrudinin** [comment]
> In latest medkey file, migrations folder is empty.

Yes. It is moved inside modules/*/migrations folders, and can be installed automatically.

**Comment by dgrudinin** [comment]
> Hi Dude,
> I have installed the latest version of medkey. when I use php bin cli/migrate this command i receive Unknown command: cli/migrate error.kindly help me.

Try command `php bin migrate`, without `cli`.

**Comment by madhu6759** [comment]
![sqlerror](https://user-images.githubusercontent.com/46740847/53153032-2d908000-35dd-11e9-9312-26c70e5a7ac0.PNG)
I am getting duplicate table error.

**Comment by madhu6759** [comment]
![sql2](https://user-images.githubusercontent.com/46740847/53153138-8bbd6300-35dd-11e9-8080-f5712a03db73.PNG)
These error too!!

**Comment by dgrudinin** [comment]
> ![sqlerror](https://user-images.githubusercontent.com/46740847/53153032-2d908000-35dd-11e9-9312-26c70e5a7ac0.PNG)
> I am getting duplicate table error.

If you are trying to install newer verison of Medkey (from repository) on the same database, which was filled by Medkey v0.2.0 migrations and seeds, then it is not correct.

Create new database, set it in config file db connection settings, and install migrations on it.

**Comment by madhu6759** [comment]
i have installed this in the new database even in the new server.But receiving this issue.

**Comment by dgrudinin** [comment]
> i have installed this in the new database even in the new server.But receiving this issue.

Ok, we'll check it up today, but later. Please, create on this problem a new issue, I'll write checkup result  there.

**Comment by madhu6759** [comment]
ya sure.
